In [24]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras import utils
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split

In [15]:
matplotlib.style.use('ggplot')
%matplotlib inline

In [16]:
wine_collection_df = pd.read_csv('wine_collection.csv', sep = ';')

In [ ]:
wine_collection_df.head()

In [26]:
del wine_collection_df['Color']

In [40]:
del wine_collection_df['№']

In [41]:
wine_collection_df.head()

,Alcohol,Malic and Apple Acid,Ash,Alcalinity of Ash,Magnesium,Total Phenols,Flavanoids,Nonflavanoid Phenols,Proanthocyanins,Intensity,Hue,OD280_OD315_of_Deluted_Wines,Proline,Desired
0,13.01,2.11,2.63,20.32,116,3.27,2.92,0.31,2.81,4.82,0.90,3.78,1210,1
1,14.06,1.72,2.82,11.49,127,3.06,3.11,0.31,2.58,6.96,0.89,3.34,1406,0
2,14.34,2.48,2.81,15.34,130,3.50,3.41,0.38,1.84,4.71,0.92,2.97,1440,1
3,14.05,1.76,2.12,19.43,106,3.87,3.23,0.35,2.07,6.75,0.94,3.71,1004,0
4,14.38,1.87,2.35,11.63,107,3.39,2.93,0.37,2.48,7.55,1.02,3.61,1229,1

In [27]:
wine_collection_df['Desired'].value_counts(normalize = True)

Desired
0    0.561798
1    0.438202
Name: proportion, dtype: float64

In [28]:
X = wine_collection_df['Desired']
y = wine_collection_df.drop('Desired', axis = 1)

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 12345, test_size = 0.33)

In [30]:
X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values

In [31]:
y_train_bin = utils.to_categorical(y_train)
y_test_bin = utils.to_categorical(y_test)

In [32]:
y_train_bin[0:5]

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [37]:
# model = Sequential()
# model.add(Dense(9, input_dim = 13, activation = 'relu'))
# model.add(Dense(10, activation = 'relu'))
# model.add(Dense(3, activation = 'softmax'))
# model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
# model.fit(X_train, y_train_bin, epochs = 300, batch_size = 10)

In [38]:
# scores = model.evaluate(X_test, y_test_bin)
# print(f"\nAccuracy: {scores[1] * 100}")

In [39]:
# predictions = model.predict(X_test)
# print(predictions[0:5])